import { readFile } from "node:fs/promises";
import { test } from "node:test";
import assert from "node:assert/strict";

const requiredAnchors = ["why", "install", "workflows", "evidence", "community", "faq"];

test("site data defines the institutional landing page contract", async () => {
  const source = await readFile(new URL("../src/data/site.ts", import.meta.url), "utf8");

  assert.match(source, /Fable Harness/);
  assert.match(source, /organize memory context into traces and manageable notes/);
  assert.match(source, /trace engine/i);
  assert.match(source, /Install the Fable-Harness skill/);
  assert.doesNotMatch(source, /npx @aao-sh\/fable-harness "\.\/path\/to\/project" --agent auto/);
  assert.doesNotMatch(source, /label: "npm"/);
  assert.doesNotMatch(source, /label: "npx"/);
  assert.doesNotMatch(source, /label: "yarn"/);
  assert.doesNotMatch(source, /label: "pip"/);
  assert.match(source, /Product Design/);
  assert.match(source, /Creative Production/);
  assert.match(source, /Figma/);
  assert.match(source, /Canva/);
  assert.match(source, /kicker: "Community"/);
  assert.match(source, /Join the community and help build open source together\./);
  assert.match(source, /label: "Organization"/);
  assert.match(source, /href: "https:\/\/aao\.sh"/);
  assert.match(source, /repoUrl: "https:\/\/github\.com\/aao-sh\/fable-harness"/);
  assert.match(source, /licenseUrl: "https:\/\/github\.com\/aao-sh\/fable-harness\/blob\/main\/LICENSE"/);
  assert.doesNotMatch(source, /github\.com\/AAO-SH/);
  assert.doesNotMatch(source, /image: "\/assets\/workflows\//);
  assert.match(source, /label: "GitHub", href: "https:\/\/github\.com\/aao-sh", icon: "github"/);
  assert.match(source, /label: "Discord"[\s\S]*label: "Telegram"[\s\S]*label: "GitHub"[\s\S]*label: "Organization"/);
  assert.match(source, /icon: "github"/);
  assert.match(source, /icon: "telegram"/);
  assert.match(source, /icon: "discord"/);
  assert.match(source, /iconSrc: "\/assets\/brand\/aao-icon-white\.svg"/);
  assert.doesNotMatch(source, /kicker: "Open source"/);
  assert.doesNotMatch(source, /label: "MIT License"/);

  for (const anchor of requiredAnchors) {
    assert.match(source, new RegExp(`id: "${anchor}"`));
  }
});

test("page source exposes all stable section anchors", async () => {
  const source = await readFile(new URL("../src/pages/index.astro", import.meta.url), "utf8");
  const hero = await readFile(new URL("../src/components/Hero.astro", import.meta.url), "utf8");

  for (const anchor of requiredAnchors) {
    assert.match(`${source}\n${hero}`, new RegExp(`id=\\{site\\.sections\\.${anchor}\\.id\\}|id="${anchor}"`));
  }

  assert.doesNotMatch(source, /InstallPanel/);
  assert.doesNotMatch(source, /install-section/);
  assert.match(hero, /id=\{site\.sections\.install\.id\}/);
  assert.match(hero, /hero-command-note/);
  assert.match(hero, /site\.install\.manualNote/);
  assert.doesNotMatch(hero, /hero-field-note/);
  assert.doesNotMatch(hero, /hero-actions/);
  assert.match(source, /id=\{site\.sections\.evidence\.id\}[^>]*hidden/);
  assert.match(source, /<EvidenceLoop \/>/);
  assert.match(source, /class="plugin-panel"[^>]*hidden/);
  assert.match(source, /site\.plugins\.map/);
  assert.match(source, /id=\{site\.sections\.faq\.id\}[^>]*hidden/);
  assert.match(source, /title="Adoption questions\."/);
  assert.doesNotMatch(source, /Adoption questions, answered compactly\./);
  assert.match(source, /<Faq \/>/);
});

test("page uses a shared section heading component for repeated headings", async () => {
  const source = await readFile(new URL("../src/pages/index.astro", import.meta.url), "utf8");
  const component = await readFile(new URL("../src/components/SectionHeading.astro", import.meta.url), "utf8");

  assert.match(source, /import SectionHeading from "@\/components\/SectionHeading\.astro";/);
  assert.equal([...source.matchAll(/<SectionHeading/g)].length, 4);
  assert.match(component, /interface Props/);
  assert.match(component, /class:list/);
});

test("pages workflow rebuilds when release data changes", async () => {
  const workflow = await readFile(new URL("../.github/workflows/pages.yml", import.meta.url), "utf8");
  const nojekyll = await readFile(new URL("../public/.nojekyll", import.meta.url), "utf8");

  assert.match(workflow, /release:\s*\n\s*types:\s*\[published, edited, deleted\]/);
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /npm run build/);
  assert.match(workflow, /actions\/upload-pages-artifact@v\d+/);
  assert.match(workflow, /actions\/deploy-pages@v\d+/);
  assert.doesNotMatch(workflow, /jekyll-build-pages/);
  assert.match(nojekyll, /Disable Jekyll/);
});

test("global background uses a mechanical workshop atmosphere behind the blueprint grid", async () => {
  const style = await readFile(new URL("../src/styles/global.css", import.meta.url), "utf8");
  const bodyBlock = style.match(/body\s*\{([\s\S]*?)\n\}/)?.[1] ?? "";

  assert.match(style, /html\s*\{[\s\S]*background:\s*var\(--paper\)/);
  assert.match(bodyBlock, /linear-gradient\(90deg/);
  assert.match(bodyBlock, /linear-gradient\(rgba\(109, 72, 30, 0\.08\)/);
  assert.doesNotMatch(bodyBlock, /var\(--paper\)/);
  assert.match(style, /body::before\s*\{[\s\S]*workshop-smoke-drift/);
  assert.match(style, /body::after\s*\{[\s\S]*workshop-spark-rise/);
  assert.match(style, /@keyframes workshop-smoke-drift/);
  assert.match(style, /@keyframes workshop-spark-rise/);
  assert.match(
    style,
    /@media \(prefers-reduced-motion: reduce\)\s*\{[\s\S]*body::before,[\s\S]*body::after[\s\S]*animation:\s*none !important/
  );
});

test("site source exposes theme, header brand icons, command tabs, and animated hero art", async () => {
  const packageSource = await readFile(new URL("../package.json", import.meta.url), "utf8");
  const astroConfig = await readFile(new URL("../astro.config.mjs", import.meta.url), "utf8");
  const nav = await readFile(new URL("../src/components/Nav.astro", import.meta.url), "utf8");
  const footer = await readFile(new URL("../src/components/Footer.astro", import.meta.url), "utf8");
  const hero = await readFile(new URL("../src/components/Hero.astro", import.meta.url), "utf8");
  const page = await readFile(new URL("../src/pages/index.astro", import.meta.url), "utf8");
  const workflowPlate = await readFile(new URL("../src/components/WorkflowPlate.astro", import.meta.url), "utf8");
  const latestRelease = await readFile(new URL("../src/data/latest-release.mjs", import.meta.url), "utf8");
  const traceEngineScene = await readFile(new URL("../src/scripts/trace-engine-scene.ts", import.meta.url), "utf8");
  const attribution = await readFile(new URL("../public/assets/ATTRIBUTION.md", import.meta.url), "utf8");
  const script = await readFile(new URL("../src/components/SiteScript.astro", import.meta.url), "utf8");
  const style = await readFile(new URL("../src/styles/global.css", import.meta.url), "utf8");

  assert.match(packageSource, /"three"/);
  assert.match(astroConfig, /manualChunks/);
  assert.match(astroConfig, /three-renderer/);
  assert.match(astroConfig, /three-geometry/);
  assert.match(astroConfig, /three-materials/);
  assert.match(nav, /<span class="brand-butterfly"/);
  assert.match(nav, /import \{ Image \} from "astro:assets"/);
  assert.doesNotMatch(nav, /<ButterflyIcon class="brand-butterfly"/);
  assert.match(nav, /steampunk-butterfly\.webp/);
  assert.match(nav, /<Image[\s\S]*class="flight-butterfly-mark"/);
  assert.doesNotMatch(nav, /<ButterflyIcon class="flight-butterfly-mark"/);
  assert.match(nav, /https:\/\/aao\.sh/);
  assert.match(nav, /aao-icon-black\.svg/);
  assert.match(nav, /aao-icon-white\.svg/);
  assert.match(nav, /data-aao-icon/);
  assert.match(footer, /import \{ getLatestReleaseFooter \} from "@\/data\/latest-release\.mjs";/);
  assert.match(footer, /const latestRelease = await getLatestReleaseFooter\(\);/);
  assert.match(footer, /href="https:\/\/aao\.sh"/);
  assert.match(footer, /<img[\s\S]*src="\/assets\/brand\/aao-icon-white\.svg"/);
  assert.match(footer, /AAO\.sh Community/);
  assert.match(footer, /https:\/\/github\.com\/aao-sh\/fable-harness\/graphs\/contributors/);
  assert.match(footer, /Released under the <a href="https:\/\/github\.com\/aao-sh\/fable-harness\/blob\/main\/LICENSE">MIT License<\/a>/);
  assert.match(footer, /<br \/>/);
  assert.match(footer, /latestRelease\.label/);
  assert.match(footer, /latestRelease\.url/);
  assert.doesNotMatch(footer, /e4a7b58|v0\.3\.0|github\.com\/AAO-SH/);
  assert.match(latestRelease, /const githubOwner = "aao-sh"/);
  assert.match(latestRelease, /const githubRepo = "fable-harness"/);
  assert.match(latestRelease, /\/releases\/latest/);
  assert.match(latestRelease, /https:\/\/github\.com\/\$\{githubOwner\}\/\$\{githubRepo\}/);
  assert.doesNotMatch(`${footer}\n${latestRelease}`, /github\.com\/AAO-SH/);
  assert.match(footer, /loading="lazy"/);
  assert.match(footer, /decoding="async"/);
  assert.doesNotMatch(nav, /data-aao-icon-hover/);
  assert.match(nav, /data-theme-toggle/);
  assert.match(nav, /theme-toggle-icon-sun/);
  assert.match(nav, /theme-toggle-icon-moon/);
  assert.doesNotMatch(nav, />Light</);
  assert.doesNotMatch(nav, />Dark</);
  assert.doesNotMatch(nav, /data-theme-toggle-label/);
  assert.match(nav, /site\.sections\.workflows\.id/);
  assert.match(nav, /site\.sections\.evidence\.id/);
  assert.match(nav, /site\.sections\.faq\.id/);
  assert.doesNotMatch(nav, />Workflows</);
  assert.doesNotMatch(nav, />Evidence</);
  assert.doesNotMatch(nav, />FAQ</);
  assert.match(hero, /site\.hero\.primaryCta/);
  assert.match(hero, /Copy install command/);
  assert.doesNotMatch(hero, /data-install-reveal-panel/);
  assert.doesNotMatch(hero, /data-install-reveal-trigger/);
  assert.doesNotMatch(hero, /class="command-card hero-command"[^>]*hidden/);
  assert.doesNotMatch(hero, /role="tablist"/);
  assert.doesNotMatch(hero, /data-command-tab/);
  assert.match(hero, /trace-engine-animation/);
  assert.match(hero, /import \{ Image \} from "astro:assets"/);
  assert.match(hero, /trace-engine-painted-base\.webp/);
  assert.doesNotMatch(hero, /trace-engine-realistic\.svg/);
  assert.match(hero, /trace-rig/);
  assert.match(hero, /data-trace-engine-scene/);
  assert.match(hero, /trace-engine-canvas/);
  assert.match(hero, /data-trace-engine-fallback/);
  assert.match(hero, /@\/scripts\/trace-engine-scene/);
  assert.match(hero, /requestIdleCallback/);
  assert.match(hero, /canLoadTraceEngineScene/);
  assert.match(hero, /min-width: 1000px/);
  assert.match(hero, /prefers-reduced-motion: reduce/);
  assert.match(hero, /trace-rig-backdrop/);
  assert.match(hero, /<Image[\s\S]*class="engine-backdrop trace-rig-backdrop"/);
  assert.match(hero, /data-responsive-loading/);
  assert.doesNotMatch(hero, /<svg[\s\S]*class="engine-backdrop trace-rig-backdrop"/);
  assert.match(workflowPlate, /import \{ Image \} from "astro:assets"/);
  assert.match(workflowPlate, /<Image/);
  assert.match(workflowPlate, /data-workflow-modal-trigger/);
  assert.doesNotMatch(workflowPlate, /plate-number/);
  assert.match(page, /workflow-grid workflow-carousel/);
  assert.match(page, /data-workflow-carousel/);
  assert.match(page, /workflow-track/);
  assert.match(page, /workflow-slide-set/);
  assert.match(page, /workflow-modal/);
  assert.match(page, /data-workflow-modal/);
  assert.match(page, /data-workflow-modal-image/);
  assert.match(page, /data-workflow-modal-close/);
  assert.match(page, /aria-hidden="true"/);
  assert.match(style, /@keyframes workflow-loop/);
  assert.match(style, /mask-image: linear-gradient/);
  assert.match(style, /animation: workflow-loop/);
  assert.match(style, /\.workflow-plate-trigger/);
  assert.match(style, /\.workflow-body\s*\{[\s\S]*justify-content: center/);
  assert.match(style, /\.workflow-body\s*\{[\s\S]*text-align: center/);
  assert.match(script, /data-workflow-modal-trigger/);
  assert.match(script, /data-workflow-carousel/);
  assert.match(script, /closest\("\.workflow-plate"\)/);
  assert.match(script, /showModal/);
  assert.doesNotMatch(style, /workflow-slide-set\[aria-hidden="true"\] \.workflow-plate\s*\{[\s\S]{0,80}pointer-events: none/);
  assert.doesNotMatch(style, /\.workflow-grid\s*\{[\s\S]{0,120}display: grid/);
  assert.match(traceEngineScene, /from "three\/src\/renderers\/WebGLRenderer\.js"/);
  assert.doesNotMatch(traceEngineScene, /from "three"/);
  assert.match(traceEngineScene, /WebGLRenderer/);
  assert.match(traceEngineScene, /PerspectiveCamera/);
  assert.match(traceEngineScene, /PlaneGeometry/);
  assert.match(traceEngineScene, /CanvasTexture/);
  assert.match(traceEngineScene, /data-render-state/);
  assert.match(traceEngineScene, /agents\.md/);
  assert.match(traceEngineScene, /notes\.md/);
  assert.match(traceEngineScene, /trace\.md/);
  assert.match(traceEngineScene, /prefers-reduced-motion/);
  assert.match(traceEngineScene, /dispose/);
  assert.match(attribution, /trace-engine-painted-base\.webp/);
  assert.match(attribution, /painted base/i);
  assert.match(attribution, /SVG\/DOM animated/i);
  assert.doesNotMatch(attribution, /retained exploratory|trace-engine-realistic|trace-engine-cinematic-sprite|fable-butterfly|public\/assets\/workflows/);
  assert.match(hero, /class="command-mode-button is-active"/);
  assert.match(hero, /rig-prompt-slip/);
  assert.match(hero, /# Make a 2D platformer game\.\.\./);
  assert.match(hero, /rig-cabinet-target/);
  assert.match(hero, /rig-drawer-light rig-drawer-memory/);
  assert.match(hero, /rig-document-slip rig-document-memory/);
  assert.match(hero, /agents\.md/);
  assert.match(hero, /rig-document-slip rig-document-notes/);
  assert.match(hero, /rig-document-slip rig-document-trace/);
  assert.match(hero, /rig-rollback-dial/);
  assert.match(hero, /rig-depth-vignette/);
  assert.doesNotMatch(hero, /rig-agent-lens/);
  assert.doesNotMatch(hero, /rig-agent-eye/);
  assert.doesNotMatch(hero, /rig-agent-probe/);
  assert.doesNotMatch(hero, /Organize workspace/);
  assert.doesNotMatch(hero, /memory\/files/);
  assert.doesNotMatch(hero, /cinematic-sprite/);
  assert.doesNotMatch(hero, /prompt-card/);
  assert.doesNotMatch(hero, /archive-cabinet/);
  assert.doesNotMatch(hero, /document-stack/);
  assert.doesNotMatch(hero, /rollback-clock/);
  assert.doesNotMatch(hero, /data-butterfly-landing/);
  assert.match(script, /data-theme-toggle/);
  assert.doesNotMatch(script, /data-install-reveal-trigger/);
  assert.doesNotMatch(script, /data-command-tab/);
  assert.match(script, /data-flight-butterfly/);
  assert.doesNotMatch(script, /aaoIconHovering/);
  assert.doesNotMatch(script, /mouseenter/);
  assert.doesNotMatch(script, /data-aao-icon-hover/);
  assert.match(script, /flightDecisionRatioFromBottom = 0\.15/);
  assert.match(script, /1 - flightDecisionRatioFromBottom/);
  assert.match(script, /headerReturnLead = 72/);
  assert.match(script, /data-flight-target/);
  assert.match(script, /site-header/);
  assert.match(style, /\[data-theme="light"\]/);
  assert.match(style, /--control-bg: #fffaeea3/);
  assert.match(style, /\.aao-link \{/);
  assert.match(style, /border: 1px solid var\(--line\)/);
  assert.match(style, /background: var\(--control-bg\)/);
  assert.match(style, /community-agent-assembly\.webp/);
  assert.match(style, /\.community-card\s*\{[\s\S]*linear-gradient[\s\S]*url\("\/assets\/art\/community-agent-assembly\.webp"\)/);
  assert.match(style, /\.plugin-panel\s*\{[\s\S]*display: grid/);
  assert.match(style, /left: 50%/);
  assert.match(style, /transform: translateX\(-50%\)/);
  assert.match(style, /hero-command-note/);
  assert.match(style, /\.command-card button\.is-active/);
  assert.match(style, /\.trace-rig/);
  assert.match(style, /\.trace-engine-canvas/);
  assert.match(style, /\[data-render-state="active"\]/);
  assert.match(style, /\.trace-rig-backdrop/);
  assert.match(style, /\.trace-rig img\.trace-rig-backdrop/);
  assert.doesNotMatch(style, /\.rig-svg-gear/);
  assert.doesNotMatch(style, /\.rig-svg-flywheel/);
  assert.doesNotMatch(style, /\.rig-svg-gauge/);
  assert.doesNotMatch(style, /cinematic-sprite|machine-light-sweep/);
  assert.match(style, /\.rig-prompt-slip/);
  assert.match(style, /\.rig-cabinet-target/);
  assert.match(style, /\.rig-document-slip/);
  assert.match(style, /\.rig-rollback-dial/);
  assert.match(style, /@keyframes rig-camera-breathe/);
  assert.doesNotMatch(style, /@keyframes rig-svg-gear-turn/);
  assert.doesNotMatch(style, /@keyframes rig-svg-gauge-pulse/);
  assert.match(style, /@keyframes rig-paper-intake/);
  assert.match(style, /@keyframes rig-drawer-store/);
  assert.match(style, /@keyframes rig-dial-rewind/);
  assert.doesNotMatch(style, /\.rig-agent-lens/);
  assert.doesNotMatch(style, /@keyframes rig-lens-scan/);
  assert.doesNotMatch(style, /steps\(/);
  assert.doesNotMatch(style, /hero-field-note/);
  assert.match(style, /filter: invert\(1\)/);
  assert.doesNotMatch(style, /\[data-theme="light"\] \.aao-link:hover img/);
  assert.match(style, /wing-beat/);
  assert.match(style, /detailed-wing-beat/);
});

test("trace engine art uses a painted base plus separately animated mechanics", async () => {
  const hero = await readFile(new URL("../src/components/Hero.astro", import.meta.url), "utf8");
  const style = await readFile(new URL("../src/styles/global.css", import.meta.url), "utf8");
  const traceEngineScene = await readFile(new URL("../src/scripts/trace-engine-scene.ts", import.meta.url), "utf8");

  assert.match(hero, /import traceEnginePaintedBase from "@\/assets\/art\/trace-engine-painted-base\.webp"/);
  assert.match(hero, /src=\{traceEnginePaintedBase\}/);
  assert.match(hero, /class="rig-prompt-slip"/);
  assert.match(hero, /rig-document-slip rig-document-memory/);
  assert.match(hero, /rig-cabinet-target/);
  assert.match(hero, /rig-rollback-dial/);
  assert.doesNotMatch(hero, /trace-engine-realistic\.svg/);
  assert.doesNotMatch(hero, /trace-engine-cinematic-sprite\.webp/);
  assert.match(style, /\.trace-rig img\.trace-rig-backdrop/);
  assert.match(style, /@keyframes rig-paper-intake/);
  assert.match(style, /@keyframes rig-document-settle/);
  assert.match(style, /@keyframes rig-dial-rewind/);
  assert.match(traceEngineScene, /createPaperPlane\("Prompt"/);
  assert.match(traceEngineScene, /createPaperPlane\("agents\.md"/);
  assert.match(traceEngineScene, /makeClockTexture/);
});
